version: '3.5'
services:
  swanaudio:
    image: pitchplay/scala-dev:jdk8-web
    command: '~run'
    volumes:
      - .:/usr/src/app
      - /root/.ivy2
    ports:
      - "9443:9443"
      - "9000:9000"
