version: '3.5'
services:
  swanaudio:
    image: swanaudio/scala-node
    command: '~run'
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /root/.ivy2
    ports:
      - "9443:9443"
      - "9000:9000"
